apiVersion: v1
kind: Service
metadata:
  name: nxiq-service-loadbalancer
  namespace: learn-k8s-channel
spec:
  selector: 
    app: nexus-iq-server
  type: LoadBalancer 
  ports:
    - name: application 
      protocol: TCP
      port: 8070
      targetPort: 8070
    - name: admin
      protocol: TCP
      port: 8071
      targetPort: 8071
