apiVersion: v1
kind: Service
metadata:
  name: nexus-service-loadbalancer
  namespace: learn-k8s-channel
spec:
  selector: 
    app: nexus-server
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

